name: 'DO NOT MERGE'
description: 'Make PRs with "do not merge" labels or tags unmergable.'
inputs:
  label:
    description: 'Label value'
    default: 'DO NOT MERGE'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
