on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize]

jobs:
  dnm:
    runs-on: ubuntu-latest
    name: Do Not Merge check
    steps:
      - name: Checking for DNM markers
        id: dnm
        uses: booleangate/github-do-not-merge@test
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          label: 'DO NOT MERGE'
